worker_processes auto;

events { worker_connections 1024; }

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    server {
        listen 80;

        # Cliente web
        location / {
            root /var/www/web;
            index index.html;
        }

        # Vídeo bajo demanda (HLS)
        location /vod/ {
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
            root /var/www;
            add_header Cache-Control no-cache;
        }

        # Directo HLS generado en caliente
        location /live/ {
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
            root /var/www;
        }

        # HLS adaptativo (segments + playlists)
        location /hls/ {
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
            alias /var/www/hls/;
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Headers *;
        }
    }
}

# Servidor RTMP
rtmp {
    server {
        listen 1935;

        application live {
            live on;                # Streaming en directo
            hls on;                 # Activar HLS
            hls_path /var/www/hls;  # Carpeta donde guardar segmentos
            hls_fragment 3;
            hls_playlist_length 10;
            hls_cleanup on;
            hls_nested off;         # desactivar subcarpetas; usa /hls/<key>.m3u8
            allow publish all;
            allow play all;
        }
    }
}
